version: 2.1

orbs:
  node: circleci/node@4.1

jobs:
  hello-world:
    docker:
      image: cimg/node:15.1
    
    steps:
      - checkout
      - run: echo "Hello World"

workflows:
  say-hello-world:
    jobs:
      - hello-world