version: 2.1

aliases:
  - &docker
    - image: cimg/node:15.1

jobs:
  build:
    docker: *docker
    steps:
      - checkout
      - run: echo "This is build job"
  test:
    docker: *docker
    steps: 
      - checkout
      - run: echo "This is test job"

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build