version: 2.1

aliases:
  - &docker
    - image: cimg/node:15.1

jobs:
  build:
    docker: *docker
    steps:
      - checkout
      - run: echo "This is build job"
  shell-test:
    docker: *docker
    steps:
        - checkout
        - run:
            name: Run Shell Script File
            command: |
              cd ./scripts/demo
              chmod 755 helloworld.sh
              ./helloworld.sh
  test:
    docker: *docker
    steps: 
      - checkout
      - run: echo "This is test job"

workflows:
  build_and_test:
    jobs:
      - build
      - shell-test:
          requires:
            - build
      - test:
          requires:
            - build
          filters:
              branches:
                only:
                  - main