version: 2.1

aliases:
  - &docker
    - image: cimg/node:15.1
  - &restore_yarn_cache
    restore_cache:
      name: Restore yarn cache
      key: v1-node-{{ arch }}-{{ checksum "yarn.lock" }}-yarn
  - &restore_node_modules_cache
    restore_cache:
      name: Restore node_modules cache
      key: v1-node-{{ arch }}-{{ .Branch }}-{{ checksum "yarn.lock" }}-node_modules

orbs:
  node: circleci/node@4.1
  aws-ecr: circleci/aws-ecr@7.0.0
  aws-ecs: circleci/aws-ecs@2.2.1

jobs:
  setup:
    docker: *docker
    steps:
      - checkout
      - run:
          name: NodeJS Version
          command: node --version
      - *restore_yarn_cache
      - run:
          name: Install Package
          command: yarn --frozen-lockfile --cache-folder ~/.cache/yarn
      - save_cache:
          name: Save yarn cache for future installs
          key: v1-node-{{ arch }}-{{ checksum "yarn.lock" }}-yarn
          paths:
            - ~/.cache/yarn
      - save_cache:
          name: Save node_modules cache
          key: v1-node-{{ arch }}-{{ .Branch }}-{{ checksum "yarn.lock" }}-node_modules
          paths:
            - node_modules

  lint:
    docker: *docker

    steps:
      - checkout
      - *restore_node_modules_cache
      - run: yarn lint
  
  test:
    docker: *docker

    steps:
      - checkout
      - *restore_node_modules_cache
      - run: yarn test

  build:
    docker: *docker

    steps:
      - checkout
      - *restore_node_modules_cache
      - run: yarn build



workflows:
  build-and-deploy:
    jobs:
      - setup
      - test:
          requires:
            - setup
      - lint:
          requires:
            - setup
      - build:
          requires:
            - test
            - lint
      - aws-ecr/build-and-push-image:
          docker: *docker
          context: AWS
          repo: ci-cd
          tag: "latest,${CIRCLE_SHA1}"
          path: .
          remote-docker-layer-caching: true
          setup-remote-docker: true
          requires:
            - build
      - aws-ecs/deploy-service-update:
          context: AWS
          family: ci-cd-task
          cluster-name: 'ci-cd-cluster'
          container-image-name-updates: "container=ci-cd-task,tag=${CIRCLE_SHA1}"
          requires:
            - aws-ecr/build-and-push-image
      